Add OIDC options and tests
mohammed90/caddy-ngrok-listener pull request #17
Opened 2023-03-15 13:09 UTC by jtszalay

Resolves https://github.com/mohammed90/caddy-ngrok-listener/issues/15

2023-03-15 15:52 UTC, jtszalay commented
After this PR is reviewed and if all looks good I should be able to knock out OAuth and Webhook Verification immediately after as they're the same pattern! 🎉

2023-03-24 10:37 UTC, jtszalay commented
This one is ready for review!

2023-05-12 18:04 UTC, mohammed90 requested changes
Alright, let's try to pick up from where we left 😄

2023-05-12 18:04 UTC, mohammed90 commented on oidc.go
> +
Change the check to `len(...) > 0`. See https://github.com/mohammed90/caddy-ngrok-listener/commit/8d3ac56e60cb8b5cd36ee10abb683565ee140adb for earlier unintended bug.

2023-05-12 18:04 UTC, mohammed90 commented on oidc.go
> +
To be safe, should it have `strings.TrimSpace`?

2023-08-21 07:36 UTC, mohammed90 commented on oidc.go
> +func (o *oidc) Provision(caddy.Context) error {
Ah, I see now unexporting the method breaks the testing facade. That's alright.

2023-08-21 08:07 UTC, mohammed90 approved these changes
Thank you for all your work on this! I'll try to pick up 🙂 If you're still interested, I'd love to have your view on how this module progresses.

2023-08-21 08:07 UTC, merged