Change `authtoken` to `auth_token` in readme as well
mohammed90/caddy-ngrok-listener pull request #27
Opened 2023-10-10 22:39 UTC by Zuruuh

I think you forgot to update the readme in [eda9c30](https://github.com/Zuruuh/caddy-ngrok-listener/commit/eda9c30f7dc2dd31a910ae4a73a61889103c2519) :+1:

2023-10-11 07:18 UTC, mohammed90 commented
> Currently the config in the readme does not work, since it was changed in eda9c30, i struggled a bit when trying to use this code sample myself. Maybe it's worth considering reverting the changes until the underlying api changes ?

But it is `authhoken` in the code 🤔

https://github.com/mohammed90/caddy-ngrok-listener/blob/master/ngrok.go#L32

How are you building it and using it?

> Also, unrelated but this is a very cool project so congrats on pulling this off 👏

Thank you! 😊 I'd love to hear feedback on how to improve it. It'll help me decide on the structure of the config and its ergonomics.

2023-10-11 08:33 UTC, Zuruuh commented
🤔 strange, the caddy docs still uses `auth_token` https://caddyserver.com/docs/modules/caddy.listeners.ngrok#tunnel
I used this module with xcaddy
```dockerfile
FROM caddy:2.7.4-builder-alpine

RUN xcaddy-build --with github.com/mohammed90/caddy-ngrok-listener
COPY ./caddy/Caddyfile /etc/caddy/Caddyfile
CMD [ "caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
```

```caddyfile
{
  servers :8080 {
    listener_wrappers {
      ngrok {
        auth_token {$NGROK_AUTH_TOKEN}
        tunnel http {
          domain {$NGROK_DOMAIN}
        }
      }
    }
  }
}

:8080 {
  # ...
}
```

This currently works, but if i replace `auth_token` with `authtoken`, I get
```
Error: adapting config using caddyfile: parsing caddyfile tokens for 'servers': /etc/caddy/Caddyfile:6 - Error during parsing: unrecognized subdirective authtoken, import chain: ['']
```

2023-10-11 09:08 UTC, mohammed90 commented
The update of the Caddy website docs is tricky. I'll check why it isn't updated.

In your case, I think the Docker cache is doing tricks. You're rebuilding an image while that line hasn't changed, so it isn't executing and rebuilding that layer. Try adding `@latest` or `@0.1.2` for the ngrok listener wrapper.

2023-10-11 09:21 UTC, Zuruuh commented
The images does rebuild when I change the Caddyfile, I've tried rebuilding it without cache (`docker compose build caddy --no-cache`) and with both `@latest` and `@v0.1.2`, and the result is still the same. I think I can provide a reproducer if you don't have the issue on your end

2023-10-11 13:46 UTC, mohammed90 commented
> The images does rebuild when I change the Caddyfile, I've tried rebuilding it without cache (`docker compose build caddy --no-cache`) and with both `@latest` and `@v0.1.2`, and the result is still the same. I think I can provide a reproducer if you don't have the issue on your end

I have tried with a fresh Docker build, and it's not reproducible. Pretty sure there's still some cache involved in your case. I saw some StackOverflow answers suggesting the use of `--pull` for the Docker build command to force cache eviction. Can you try?

By the way, the Dockerfile needs improvements as well. The xcaddy build command is `xcaddy build`, not `xcaddy-build`. Also the `-builder` image variant isn't meant to be used directly rather only to build Caddy then to copy the binary into another image (scratch or the regular Caddy image).

2023-10-11 20:45 UTC, mohammed90 commented
> I think what might be happening is the new `authtoken` is not in the latest release `0.1.2`.

Nope. It's definitely in 0.1.2. See, [here](https://github.com/mohammed90/caddy-ngrok-listener/releases/tag/v0.1.2) it says "0 commits to master since this release".

Here's the output of running the reproducer in your repo:
```
~/caddy-ngrok-authtoken-reproducer $ cat run.sh
#!/bin/sh

docker build --tag caddy-ngrok-authtoken-reproducer --target caddy --pull --no-cache .
docker run --rm --env-file .env caddy-ngrok-authtoken-reproducer caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile
~/projects/caddy-ngrok-authtoken-reproducer $ cat .env
NGROK_DOMAIN=localhost%
~/projects/caddy-ngrok-authtoken-reproducer $ cat Dockerfile                                                                                        docker24.0.5,
FROM caddy:2.7.4-builder-alpine as builder

RUN xcaddy build --with github.com/mohammed90/caddy-ngrok-listener@latest

FROM caddy:2.7.4-alpine as caddy

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
COPY Caddyfile /etc/caddy/Caddyfile
~/projects/caddy-ngrok-authtoken-reproducer $ ./run.sh
[+] Building 692.1s (11/11) FINISHED                                                                                                                                          docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                                                                          0.1s
 => => transferring dockerfile: 278B                                                                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                                                             0.1s
 => => transferring context: 2B                                                                                                                                                               0.0s
 => [internal] load metadata for docker.io/library/caddy:2.7.4-alpine                                                                                                                         4.8s
 => [internal] load metadata for docker.io/library/caddy:2.7.4-builder-alpine                                                                                                                 4.8s
 => [internal] load build context                                                                                                                                                             0.0s
 => => transferring context: 315B                                                                                                                                                             0.0s
 => [builder 1/2] FROM docker.io/library/caddy:2.7.4-builder-alpine@sha256:ec3ac7eee8b4635cb9336eb4cb201684d2cd54f6fe3bcbb61469e1114188f461                                                  59.7s
 => => resolve docker.io/library/caddy:2.7.4-builder-alpine@sha256:ec3ac7eee8b4635cb9336eb4cb201684d2cd54f6fe3bcbb61469e1114188f461                                                           0.0s
 => => sha256:ec3ac7eee8b4635cb9336eb4cb201684d2cd54f6fe3bcbb61469e1114188f461 1.43kB / 1.43kB                                                                                                0.0s
 => => sha256:46a110fde950265703eaee1a30334a3f6fdab3afcebcbb4950f6c3bd37679149 1.79kB / 1.79kB                                                                                                0.0s
 => => sha256:127fe03dcdce0131c9e3ebafc11f5184beaa08be867e816c5db21df6cf60b450 9.22kB / 9.22kB                                                                                                0.0s
 => => sha256:96526aa774ef0126ad0fe9e9a95764c5fc37f409ab9e97021e7b4775d82bf6fa 3.40MB / 3.40MB                                                                                                2.6s
 => => sha256:cc37b24bb09971feb8bf4882e861bce9db0c985a16a900adb0dc9de3f854243b 284.69kB / 284.69kB                                                                                            2.6s
 => => sha256:40a4303e95078c253686dcc16d7717644af63809efcbd753c0a999c9aad3fe72 67.01MB / 67.01MB                                                                                             44.3s
 => => sha256:359925be0f358b952dc8be63647139c5aab0fff94f7a070d88cb51dd258f80e5 155B / 155B                                                                                                    3.2s
 => => extracting sha256:cc37b24bb09971feb8bf4882e861bce9db0c985a16a900adb0dc9de3f854243b                                                                                                     0.1s
 => => sha256:756fd04581de0d1e57432e3cd2d301b8c86d38131e671e2f9084c4220db3b8a4 4.97MB / 4.97MB                                                                                               15.0s
 => => sha256:c495cf673992ff0cfc8ecda905da7c4a0a038599879c2628ae1759d124b06ef3 1.30MB / 1.30MB                                                                                               19.2s
 => => sha256:04fd3fd855f81c92bfe68959b10fb526ab8b71db1946aae1bbc93926b7461a14 406B / 406B                                                                                                   20.0s
 => => extracting sha256:40a4303e95078c253686dcc16d7717644af63809efcbd753c0a999c9aad3fe72                                                                                                    13.5s
 => => extracting sha256:359925be0f358b952dc8be63647139c5aab0fff94f7a070d88cb51dd258f80e5                                                                                                     0.0s
 => => extracting sha256:756fd04581de0d1e57432e3cd2d301b8c86d38131e671e2f9084c4220db3b8a4                                                                                                     0.2s
 => => extracting sha256:c495cf673992ff0cfc8ecda905da7c4a0a038599879c2628ae1759d124b06ef3                                                                                                     0.0s
 => => extracting sha256:04fd3fd855f81c92bfe68959b10fb526ab8b71db1946aae1bbc93926b7461a14                                                                                                     0.0s
 => [caddy 1/3] FROM docker.io/library/caddy:2.7.4-alpine@sha256:11ae052d9015105757d19caf86dc51fc14403841f2b65e93fe320f4d0e197385                                                            27.7s
 => => resolve docker.io/library/caddy:2.7.4-alpine@sha256:11ae052d9015105757d19caf86dc51fc14403841f2b65e93fe320f4d0e197385                                                                   0.0s
 => => sha256:3d1bf053476f2415b40e728c37e1112ee7551fa154a63d6f62b275c13fea8166 1.16kB / 1.16kB                                                                                                0.0s
 => => sha256:7a7b2e234b158c1e01eab04f851fc4b1a33296dbaa68c57d11815ee38a3cafaf 7.80kB / 7.80kB                                                                                                0.0s
 => => sha256:96526aa774ef0126ad0fe9e9a95764c5fc37f409ab9e97021e7b4775d82bf6fa 3.40MB / 3.40MB                                                                                                2.6s
 => => sha256:37be51084fb891c6796079e693b73f6f882266a5e66211344173031e2b0c8ffd 350.83kB / 350.83kB                                                                                            0.9s
 => => sha256:22d867aa37ac50364bf4082dc48c7d4e1b88ead3164d47855e1bbc2ef3678cfc 7.50kB / 7.50kB                                                                                                1.2s
 => => sha256:11ae052d9015105757d19caf86dc51fc14403841f2b65e93fe320f4d0e197385 1.43kB / 1.43kB                                                                                                0.0s
 => => sha256:147aa3899aa3307c28e185f53 [...]

2023-10-11 21:55 UTC, Zuruuh commented
> As you can see, it's recognizing auth_token and passing the configuration validation successfully.

Well yeah that's what wanted to show you ? Maybe there is a misunderstanding, but what I wanted to say from the start is:     

The `auth_token` directive is what currently works with `@v0.1.2`/`@latest`, but the readme says to use `authtoken`.   
As you can see with the reproducer, the config was correctly validated using the `@latest` version of this module, and the `auth_token` directive, even though according to the code and the readme, it should be using `authtoken`

2023-10-11 22:28 UTC, mohammed90 commented
> Well yeah that's what wanted to show you ?

You're right. I wasn't paying attention much. Sorry.

So I noticed something. Even though GitHub says "0 commit to master since this release" and the code in HEAD uses `authtoken`, browsing the code in the v0.1.2 tree shows `auth_token` in the code. I'm not sure what git shenanigans happened when I tagged v0.1.2. I presume this is why the Caddy website docs show `auth_token` as well.

If you don't mind, can you change `authtoken` in the code to `auth_token`? and I'll merge the PR with those. Since that's the exposed behavior (accepting `auth_token`), let's stick to that.

2023-10-11 22:54 UTC, Zuruuh commented
Done :+1: 👌

2023-10-11 22:59 UTC, mohammed90 requested changes
There's one more in line 32 of the file `ngrok.go`. GitHub won't let me comment on it. Basically change `json:"authtoken"` to `json:auth_token"`.

2023-10-11 23:18 UTC, Zuruuh commented
👍 fixed

2023-10-12 05:14 UTC, mohammed90 approved these changes
Thank you so much for catching this (and for bearing with my inattention)!

2023-10-12 05:14 UTC, merged

2023-10-12 06:16 UTC, Zuruuh commented
no problem 🙂

2023-10-14 20:13 UTC, jtszalay commented
I know this is already merged and its been a while since I looked back at this but ngrok uses `authtoken` in the standard agent configuration 
https://ngrok.com/docs/secure-tunnels/ngrok-agent/reference/config/#authtoken

2023-10-14 20:49 UTC, mohammed90 commented
> I know this is already merged and its been a while since I looked back at this but ngrok uses `authtoken` in the standard agent configuration https://ngrok.com/docs/secure-tunnels/ngrok-agent/reference/config/#authtoken

Yeah, I went back and forth on this one then settled on `authtoken` to match the ngrok docs. However, the confusion between the published docs (of this module) and what the tagged version said (as discovered through this report) lead me to settle with `auth_token`.

I'm ok with changing it to match the ngrok docs, but let the dust settle a little bit. :)