Add addtional tunnel opts for http, tls, and tcp
mohammed90/caddy-ngrok-listener pull request #4
Opened 2023-03-12 22:17 UTC by jtszalay

This should be merged after https://github.com/mohammed90/caddy-ngrok-listener/pull/3

2023-03-14 21:10 UTC, mohammed90 requested changes
Great, let's clear off some things! Thank you for the PR

2023-03-14 21:10 UTC, mohammed90 commented on http.go
> +			case "enable_compression":
The common pattern in Caddyfile for boolean toggles is to do something like `compression off`. See (Search `off`):

https://caddyserver.com/docs/caddyfile/options

https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#the-http-transport

https://caddyserver.com/docs/caddyfile/directives/php_fastcgi#index

2023-03-14 21:10 UTC, mohammed90 commented on tcp.go
> +	RemoteAddr string `json:"remoteAddr,omitempty"`
snake_case please 🙂

2023-03-14 21:10 UTC, mohammed90 commented on tcp.go
> +	AllowCIDR []string `json:"allowCidr,omitempty"`
same

2023-03-14 21:10 UTC, mohammed90 commented on tcp.go
> +	DenyCIDR []string `json:"denyCidr,omitempty"`
same

2023-03-14 21:10 UTC, mohammed90 commented on tls.go
> +	AllowCIDR []string `json:"allowCidr,omitempty"`
snake_case 🙂

2023-03-14 21:10 UTC, mohammed90 commented on tls.go
> +	DenyCIDR []string `json:"denyCidr,omitempty"`
same

2023-03-14 21:22 UTC, jtszalay commented on http.go
> +	EnableWebsocketTCPConversion bool `json:"enableWebsocketTcpConversion,omitempty"`
I'm going to swap to `websocket_tcp_converter` as that is what the standard ngrok config calls the option. https://ngrok.com/docs/ngrok-agent/config/#tunnel-definitions

2023-03-14 21:38 UTC, mohammed90 approved these changes
Great. Thanks! 🎉

2023-03-14 21:38 UTC, merged

2023-03-14 21:38 UTC, jtszalay commented
Thanks for taking the time to review all these PRs! I was trying to get a `caddy-ngrok` plugin started last month but was struggling to get the foundations together. I kept trying to figure out how to make it listen on the ngrok listener AND the default caddy listener. I didn't think to drop the incoming listener and just return the ngrok listener.

I've since come across this project this week: https://github.com/daniel-garcia/multilistener/blob/master/listener.go
Thoughts on making this a multilistener so that local address and port still work?

2023-03-16 21:35 UTC, mohammed90 commented
> Thanks for taking the time to review all these PRs! I was trying to get a `caddy-ngrok` plugin started last month but was struggling to get the foundations together.

Thank YOU for those PRs! I loved seeing them coming. They brought the project to maturity faster than it would've taken me 😁 

> I kept trying to figure out how to make it listen on the ngrok listener AND the default caddy listener.

Ignoring Caddy's listener just felt natural for the purpose of the module 😂

> I've since come across this project this week: https://github.com/daniel-garcia/multilistener/blob/master/listener.go
> Thoughts on making this a multilistener so that local address and port still work?

Intriguing! But I'm not sure whether users will naturally expect both listeners to work, because it's a "wrapper", or only ngrok's listener because it's ngrok. Do you think it's possible to have a toggle? You don't have to go the toggle route, I'm genuinely curious which way is better.

I don't personally use ngrok, even though I drafted this module, so I can't have a solid opinion on it. What do you think users expect?